from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QMessageBox
from PyQt5.QtGui import QPixmap
import pymysql
import sys
import datetime
class Ui_MainWindow(object):
    def success(self):
        self.window=QtWidgets.QMainWindow()
        self.main=Mainmenu()
        self.main.setupUi(self.window)
        MainWindow.hide()
        self.window.show()

    def messagebox(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowIcon(QtGui.QIcon('App logo.png'))
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok)
        mess.exec_()

        if mess.Ok:
            self.success()

    def warning(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowIcon(QtGui.QIcon('App logo.png'))
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok| QtWidgets.QMessageBox.Cancel)
        mess.exec_()

        if mess.Ok:
            self.Username.clear()
            self.Password.clear()

    def login(self):
        Username=self.Username.text()
        Password=self.Password.text()
        params=(Username,Password)
        conn = pymysql.connect(host="localhost",port=3306,db="dboragon",user="DBMS",password="12345")
        cursor = conn.cursor()
        cursor.callproc('login',params)
        if (len(cursor.fetchall())>0):
            self.messagebox('You are in','Congratulations')
        else:
            self.warning('Error','Please try again')
            

    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QtGui.QIcon('App logo.png'))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(853, 655)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(853, 655))
        MainWindow.setMaximumSize(QtCore.QSize(853, 655))
        MainWindow.setStyleSheet("background-color: rgb(255, 245, 163);")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 853, 655))
        self.background.setPixmap(QPixmap('LOGIN PAGE.png'))
        self.background.setObjectName("background")

        self.Username = QtWidgets.QLineEdit(self.centralwidget)
        self.Username.setGeometry(QtCore.QRect(380, 370, 401, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(15)
        self.Username.setFont(font)
        self.Username.setText("")
        self.Username.setObjectName("Email")
        self.Username.setStyleSheet("background-color: rgb(255, 255, 255);")

        self.Password = QtWidgets.QLineEdit(self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(380, 460, 401, 51))
        self.Password.setStyleSheet("background-color: rgb(255, 255, 255);")
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates Black")
        font.setPointSize(15)
        self.Password.setFont(font)
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Admin ID")

        self.Submit = QtWidgets.QPushButton(self.centralwidget)
        self.Submit.setGeometry(QtCore.QRect(380, 530, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Montserrat Alternates SemiBold")
        font.setPointSize(15)
        self.Submit.setFont(font)
        self.Submit.setObjectName('Submit')
        self.Submit.clicked.connect(self.login)
        self.Submit.setStyleSheet("QPushButton{background: orange}\QPushButton::hover{background:yellow}\QPushButton:flat{border:none}")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)  
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Oragon Login"))
        self.Submit.setText(_translate("MainWindow", "Submit"))

class Mainmenu(QMainWindow):
    def messagebox(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowIcon(QtGui.QIcon('App logo.png'))
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok|QtWidgets.QMessageBox.Cancel)
        mess.exec_()
        if mess.Ok:
            self.searchbar.clear()

    def ignore(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowIcon(QtGui.QIcon('App logo.png'))
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok|QtWidgets.QMessageBox.Cancel)
        mess.exec_()
    def cell_was_clicked(self, row, column):
        self.rowclicked = row

    def delete(self):
        try:
            delete_params=(self.tableWidget.item(self.rowclicked,0).text())
            conn = pymysql.connect(host="localhost",port=3306,db="dboragon",user="DBMS",password="12345")
            cursor = conn.cursor()
            cursor.execute("Delete from Sales_product where Product_ID=%s",delete_params)
            conn.commit()
            cursor.close()
            self.tableWidget.removeRow(self.rowclicked)
            self.view()
        except:
            self.messagebox('Error','Please click a row to delete')

    def addTable(self,columns):
        rowPosition=self.tableWidget.rowCount()
        self.tableWidget.insertRow(rowPosition)
        for i, column in enumerate(columns):
                self.tableWidget.setItem(rowPosition,i, QtWidgets.QTableWidgetItem(str(column)))
   
    def view(self):
        conn = pymysql.connect(host="localhost",port=3306,db="dboragon",user="DBMS",password="12345")
        cursor = conn.cursor()
        cursor.callproc('GetProducts')
        result = cursor.fetchall()
        self.tableWidget.setRowCount(0)
        for row in result:
                self.addTable(row)
                cursor.close()

    def update(self):
        try:
            self.product_num_cell = self.tableWidget.item(self.rowclicked, 0).text()
            self.updatewindow = QtWidgets.QMainWindow()
            self.ui = update_win(self)
            self.ui.setupUi(self.updatewindow)
            self.ui.insertData(self.product_num_cell)
            self.updatewindow.show()
        except:
            self.messagebox('Error','Please click a row to update')

    def warning(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowIcon(QtGui.QIcon('App logo.png'))
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok| QtWidgets.QMessageBox.Cancel)
        mess.exec_()

    def search_data(self):
        inputsearch=self.searchbar.text()
        conn = pymysql.connect(host="localhost",port=3306,db="dboragon",user="DBMS",password="12345")
        cursor = conn.cursor()
        cursor.execute("select * from SALES_Product where Prod_name= %s",inputsearch)
        result = cursor.fetchall()
        if (len(result)>0):
            self.messagebox('Success','Prooduct information is sucessfully gathered')
            self.tableWidget.setRowCount(0)
            for row in result:
                self.addTable(row)
                cursor.close()
        elif(inputsearch==''):
            self.warning('Error','Empty Search field')
        else:
            self.messagebox('Error','There is no such Product')
    def transact(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Transactwin()
        self.ui.setupUi(self.window)
        self.window.show()

    def insert(self):
        self.insertinwindow = QtWidgets.QMainWindow()
        self.ui = insertWin()
        self.ui.setupUi(self.insertinwindow)
        self.insertinwindow.show()
        self.view()

    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QtGui.QIcon('App Logo.png'))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(853, 655)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(853, 655))
        MainWindow.setMaximumSize(QtCore.QSize(853, 655))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 853, 655))
        self.Background.setPixmap(QPixmap('Main.png'))
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(160, 70, 681, 541))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.CustomDashLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.cellClicked.connect(self.cell_was_clicked)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.Add = QtWidgets.QPushButton(self.centralwidget)
        self.Add.setGeometry(QtCore.QRect(10, 70, 141, 61))
        self.Add.setStyleSheet("QPushButton{background:LawnGreen;border-style: solid;border-color: black;border-width: 4px;border-radius: 8px}\QPushButton::hover{background:ForestGreen}\QPushButton:pressed{background:GreenYellow}")
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Add.setFont(font)
        self.Add.setObjectName("Add")
        self.Add.clicked.connect(self.insert)
        self.Delete = QtWidgets.QPushButton(self.centralwidget)
        self.Delete.setGeometry(QtCore.QRect(10, 130, 141, 61))
        self.Delete.setStyleSheet("QPushButton{background:LawnGreen;border-style: solid;border-color: black;border-width: 4px;border-radius: 8px}\QPushButton::hover{background:ForestGreen}\QPushButton:pressed{background:GreenYellow}")
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Delete.setFont(font)
        self.Delete.setObjectName("Delete")
        self.Delete.clicked.connect(self.delete)
        self.Edit = QtWidgets.QPushButton(self.centralwidget)
        self.Edit.setGeometry(QtCore.QRect(10, 190, 141, 61))
        self.Edit.setStyleSheet("QPushButton{background:LawnGreen;border-style: solid;border-color: black;border-width: 4px;border-radius: 8px}\QPushButton::hover{background:ForestGreen}\QPushButton:pressed{background:GreenYellow}")
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Edit.setFont(font)
        self.Edit.setObjectName("Edit")
        self.Edit.clicked.connect(self.update)
        self.Search = QtWidgets.QPushButton(self.centralwidget)
        self.Search.setGeometry(QtCore.QRect(10, 320, 141, 61))
        self.Search.setStyleSheet("QPushButton{background:LawnGreen;border-style: solid;border-color: black;border-width: 4px;border-radius: 8px}\QPushButton::hover{background:ForestGreen}\QPushButton:pressed{background:GreenYellow}")
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Search.setFont(font)
        self.Search.setObjectName("Search")
        self.Search.clicked.connect(self.search_data)
        self.Refresh = QtWidgets.QPushButton(self.centralwidget)
        self.Refresh.setGeometry(QtCore.QRect(10, 430, 141, 61))
        self.Refresh.setStyleSheet("QPushButton{background:LawnGreen;border-style: solid;border-color: black;border-width: 4px;border-radius: 8px}\QPushButton::hover{background:ForestGreen}\QPushButton:pressed{background:GreenYellow}")
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Refresh.setFont(font)
        self.Refresh.setObjectName("Refresh")
        self.Refresh.clicked.connect(self.view)
        self.Order = QtWidgets.QPushButton(self.centralwidget)
        self.Order.setGeometry(QtCore.QRect(10, 550, 141, 61))
        self.Order.setStyleSheet("QPushButton{background:LawnGreen;border-style: solid;border-color: black;border-width: 4px;border-radius: 8px}\QPushButton::hover{background:ForestGreen}\QPushButton:pressed{background:GreenYellow}")
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Order.setFont(font)
        self.Order.setObjectName("Order")
        self.Order.clicked.connect(self.transact)
        self.searchbar = QtWidgets.QLineEdit(self.centralwidget)
        self.searchbar.setGeometry(QtCore.QRect(10, 280, 131, 21))
        self.searchbar.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.view()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Add.setText(_translate("MainWindow", "ADD"))
        self.Delete.setText(_translate("MainWindow", "DELETE"))
        self.Edit.setText(_translate("MainWindow", "EDIT"))
        self.Search.setText(_translate("MainWindow", "SEARCH"))
        self.Order.setText(_translate("MainWindow", "ORDER"))
        self.Refresh.setText(_translate("MainWindow","REFRESH"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Product ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Product Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Price"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Type"))

class Ui_Transactwin(object):
    def messagebox(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowIcon(QtGui.QIcon('App logo.png'))
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok|QtWidgets.QMessageBox.Cancel)
        mess.exec_()
    def confirmation(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowIcon(QtGui.QIcon('App logo.png'))
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok|QtWidgets.QMessageBox.No)
        mess.exec_()

    def addtransaction(self):
        currentDT = datetime.datetime.now()
        name=str(self.NAME_LE.text())
        QTY=int(self.QTY_LE.text())
        Customer=self.Customer_name.text()
        conn = pymysql.connect(host="localhost",port=3306,db="dboragon",user="DBMS",password="12345")
        cursor = conn.cursor()
        cursor.execute('select Prod_QTY, Prod_Price from SALES_Product where Prod_Name=%s',name)
        result=cursor.fetchone()
        checker=int(result[0])
        total=int(result[1])
        total=total*QTY

        if QTY ==0:
            self.messagebox('Error','Enter a value')
            self.NAME_LE.clear()
            self.Customer_name.clear()
            self.QTY_LE.clear()

        elif checker >= QTY:
            cursor.execute('insert into sales_customerinfo (Customer_Name) values (%s)',(Customer))
            cursor.execute('update sales_product set Prod_QTY= Prod_QTY-\'{0}\' where Prod_Name= \'{1}\''.format(QTY,name))
            cursor.execute('select Customer_ID from sales_customerinfo')
            result=cursor.fetchone()
            customerid=result[0]
            cursor.execute('select Admin_ID from admin_info')
            adminres=cursor.fetchone()
            admin_id=adminres[0]
            cursor.execute('Select Prod_Name from sales_product where Prod_Name=%s',name)
            product=cursor.fetchone()
            product_name=product[0]
            cursor.execute('insert into sales_order (Customer_ID, Admin_ID,Prod_Name, Prod_Qty, Total_Price, Transaction_Date) values (%s,%s,%s,%s,%s,%s)',
            (customerid,admin_id,product_name,QTY,total,currentDT))
            conn.commit()
            self.RECEIPT_LABEL.setText("Total Price: %d" %total)

        else:
            self.NAME_LE.clear()
            self.QTY_LE.clear()

    def addTable(self,columns):
        rowPosition=self.tableWidget.rowCount()
        self.tableWidget.insertRow(rowPosition)
        for i, column in enumerate(columns):
                self.tableWidget.setItem(rowPosition,i, QtWidgets.QTableWidgetItem(str(column)))

    def viewtransact(self):
        conn = pymysql.connect(host="localhost",port=3306,db="dboragon",user="DBMS",password="12345")
        cursor = conn.cursor()
        cursor.callproc('getorder')
        result = cursor.fetchall()
        self.tableWidget.setRowCount(0)
        for row in result:
                self.addTable(row)
                cursor.close()

    def setupUi(self, Transacrwin):
        Transacrwin.setWindowIcon(QtGui.QIcon('App Logo.png'))
        Transacrwin.setObjectName("Transacrwin")
        Transacrwin.resize(853, 655)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Transacrwin.sizePolicy().hasHeightForWidth())
        Transacrwin.setSizePolicy(sizePolicy)
        Transacrwin.setMinimumSize(QtCore.QSize(853, 655))
        Transacrwin.setMaximumSize(QtCore.QSize(853, 655))
        Transacrwin.setSizeIncrement(QtCore.QSize(853, 655))
        Transacrwin.setBaseSize(QtCore.QSize(853, 655))
        self.centralwidget = QtWidgets.QWidget(Transacrwin)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 853, 655))
        self.Background.setPixmap(QPixmap('Wallpaper_TRANSACTIONWINDOW.png'))
        self.Background.setObjectName("Background")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(260, 190, 571, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(90)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.SUBMIT = QtWidgets.QPushButton(self.centralwidget)
        self.SUBMIT.setStyleSheet("QPushButton{background:LawnGreen;border-style: solid;border-color: black;border-width: 4px;border-radius: 8px}\QPushButton::hover{background:ForestGreen}\QPushButton:pressed{background:GreenYellow}")
        self.SUBMIT.setGeometry(QtCore.QRect(30, 310, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SUBMIT.setFont(font)
        self.SUBMIT.setObjectName("SUBMIT")
        self.SUBMIT.clicked.connect(self.addtransaction)
        self.NAME_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.NAME_LE.setGeometry(QtCore.QRect(30, 120, 191, 51))
        self.NAME_LE.setText("")
        self.NAME_LE.setObjectName("NAME_LE")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.NAME_LE.setFont(font)
        self.QTY_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.QTY_LE.setGeometry(QtCore.QRect(30, 230, 191, 51))
        self.QTY_LE.setObjectName("QTY_LE")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.QTY_LE.setFont(font)
        self.NAME_LABEL = QtWidgets.QLabel(self.centralwidget)
        self.NAME_LABEL.setGeometry(QtCore.QRect(30, 70, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.NAME_LABEL.setFont(font)
        self.NAME_LABEL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.NAME_LABEL.setObjectName("NAME_LABEL")
        self.QTY_LABEL = QtWidgets.QLabel(self.centralwidget)
        self.QTY_LABEL.setGeometry(QtCore.QRect(30, 180, 191, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.QTY_LABEL.setFont(font)
        self.QTY_LABEL.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.QTY_LABEL.setObjectName("QTY_LABEL")
        self.RECEIPT_LABEL = QtWidgets.QLabel(self.centralwidget)
        self.RECEIPT_LABEL.setGeometry(QtCore.QRect(10, 430, 241, 211))
        self.RECEIPT_LABEL.setStyleSheet("background-color: transparent; color: LawnGreen;")
        self.RECEIPT_LABEL.setObjectName("RECEIPT_LABEL")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.RECEIPT_LABEL.setFont(font)
        self.BOR_LINE1 = QtWidgets.QFrame(self.centralwidget)
        self.BOR_LINE1.setGeometry(QtCore.QRect(0, 50, 851, 20))
        self.BOR_LINE1.setStyleSheet("color: rgb(0, 0, 0);")
        self.BOR_LINE1.setFrameShape(QtWidgets.QFrame.HLine)
        self.BOR_LINE1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BOR_LINE1.setObjectName("BOR_LINE1")
        self.TRANSACTIONPAGE = QtWidgets.QLabel(self.centralwidget)
        self.TRANSACTIONPAGE.setGeometry(QtCore.QRect(290, 10, 321, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.TRANSACTIONPAGE.setFont(font)
        self.TRANSACTIONPAGE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.TRANSACTIONPAGE.setObjectName("TRANSACTIONPAGE")
        self.BOR_LINE2 = QtWidgets.QFrame(self.centralwidget)
        self.BOR_LINE2.setGeometry(QtCore.QRect(0, 20, 291, 20))
        self.BOR_LINE2.setStyleSheet("color: rgb(0, 0, 0);")
        self.BOR_LINE2.setFrameShape(QtWidgets.QFrame.HLine)
        self.BOR_LINE2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BOR_LINE2.setObjectName("BOR_LINE2")
        self.BOR_LINE3 = QtWidgets.QFrame(self.centralwidget)
        self.BOR_LINE3.setGeometry(QtCore.QRect(550, 20, 301, 20))
        self.BOR_LINE3.setStyleSheet("color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(255, 255, 255, 255), stop:0.373979 rgba(255, 255, 255, 255), stop:0.373991 rgba(33, 30, 255, 255), stop:0.624018 rgba(33, 30, 255, 255), stop:0.624043 rgba(255, 0, 0, 255), stop:1 rgba(255, 0, 0, 255));")
        self.BOR_LINE3.setFrameShape(QtWidgets.QFrame.HLine)
        self.BOR_LINE3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.BOR_LINE3.setObjectName("BOR_LINE3")
        self.viewtrans = QtWidgets.QPushButton(self.centralwidget)
        self.viewtrans.setStyleSheet("QPushButton{background:LawnGreen;border-style: solid;border-color: black;border-width: 4px;border-radius: 8px}\QPushButton::hover{background:ForestGreen}\QPushButton:pressed{background:GreenYellow}")
        self.viewtrans.setGeometry(QtCore.QRect(30, 370, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.viewtrans.setFont(font)
        self.viewtrans.setObjectName("viewtrans")
        self.viewtrans.clicked.connect(self.viewtransact)
        self.NAME_LABEL_2 = QtWidgets.QLabel(self.centralwidget)
        self.NAME_LABEL_2.setGeometry(QtCore.QRect(270, 70, 211, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.NAME_LABEL_2.setFont(font)
        self.NAME_LABEL_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.NAME_LABEL_2.setObjectName("NAME_LABEL_2")
        self.Customer_name = QtWidgets.QLineEdit(self.centralwidget)
        self.Customer_name.setGeometry(QtCore.QRect(280, 120, 551, 51))
        self.Customer_name.setText("")
        self.Customer_name.setObjectName("Customer_name")
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Customer_name.setFont(font)
        Transacrwin.setCentralWidget(self.centralwidget)

        self.retranslateUi(Transacrwin)
        QtCore.QMetaObject.connectSlotsByName(Transacrwin)
        self. viewtransact()
    def retranslateUi(self, Transacrwin):
        _translate = QtCore.QCoreApplication.translate
        Transacrwin.setWindowTitle(_translate("Transacrwin", "Transaction"))
        self.SUBMIT.setText(_translate("Transacrwin", "Submit"))
        self.NAME_LABEL.setText(_translate("Transacrwin", "Name:"))
        self.QTY_LABEL.setText(_translate("Transacrwin", "Quantity:"))
        self.TRANSACTIONPAGE.setText(_translate("Transacrwin", "TRANSACTION PAGE"))
        self.viewtrans.setText(_translate("Transacrwin", "View All Transaction"))
        self.NAME_LABEL_2.setText(_translate("Transacrwin", "Customer Name:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Transacrwin", "Order ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Transacrwin", "Customer ID"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Transacrwin", "Admin ID"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Transacrwin", "Product Name"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Transacrwin", "Product Quantity"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Transacrwin", "Total Price"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Transacrwin", "Date of Transaction"))

class update_win(QMainWindow):
    def messagebox(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowIcon(QtGui.QIcon('App logo.png'))
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok|QtWidgets.QMessageBox.Cancel)
        mess.exec_()
        
    def insertData(self, product_num_cell):
        conn = pymysql.connect(host="localhost",port=3306,db="dboragon",user="DBMS",password="12345")
        cur = conn.cursor()
        cur.callproc('GetProducts')
        result = cur.fetchall()
        products = {}
        for product_num in range(0, len(result)):
            products[result[product_num][0]] = result[product_num]
        for product_number in products:
            if (product_number==product_num_cell):
                self.prod_id_LE.setText(products[product_number][0])
                self.prodname_LE.setText(products[product_number][1])
                self.prodqtyLE.setText(products[product_number][2])
                self.Prodprice_LE.setText(products[product_number][3])
                self.prodtype_LE.setText(products[product_number][4])
                break
        self.product_num_cell = product_num_cell
    def update_data(self):
        conn = pymysql.connect(host="localhost",port=3306,db="dboragon",user="DBMS",password="12345")
        cursor = conn.cursor()
        Name=self.prodname_LE.text()
        qty=self.prodqtyLE.text()
        Price=self.Prodprice_LE.text()
        prod_type=self.prodtype_LE.text()
        cursor.callproc('Update_Sales',[Name,qty,Price,prod_type,self.product_num_cell])
        conn.commit()
        self.messagebox('Sucess','Row has been updated')
        
    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QtGui.QIcon('App Logo.png'))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(653, 455)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(653, 455))
        MainWindow.setMaximumSize(QtCore.QSize(653, 455))
        MainWindow.setSizeIncrement(QtCore.QSize(653, 455))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 653, 455))
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.Background.setPixmap(QPixmap('product.png'))
        self.Product_Qty = QtWidgets.QLabel(self.centralwidget)
        self.Product_Qty.setGeometry(QtCore.QRect(40, 90, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Product_Qty.setFont(font)
        self.Product_Qty.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Product_Qty.setObjectName("Product_Qty")
        self.Product_name = QtWidgets.QLabel(self.centralwidget)
        self.Product_name.setGeometry(QtCore.QRect(40, 150, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Product_name.setFont(font)
        self.Product_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Product_name.setObjectName("Product_name")
        self.Product_price = QtWidgets.QLabel(self.centralwidget)
        self.Product_price.setGeometry(QtCore.QRect(40, 210, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Product_price.setFont(font)
        self.Product_price.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Product_price.setObjectName("Product_price")
        self.Product_ID = QtWidgets.QLabel(self.centralwidget)
        self.Product_ID.setGeometry(QtCore.QRect(40, 270, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Product_ID.setFont(font)   
        self.Product_ID.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Product_ID.setObjectName("Product_ID")
        self.Product_type = QtWidgets.QLabel(self.centralwidget)
        self.Product_type.setGeometry(QtCore.QRect(40, 330, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Product_type.setFont(font)
        self.Product_type.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Product_type.setObjectName("Product_type")
        self.ADD_PRODUCT = QtWidgets.QLabel(self.centralwidget)
        self.ADD_PRODUCT.setGeometry(QtCore.QRect(200, 20, 221, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ADD_PRODUCT.setFont(font)
        self.ADD_PRODUCT.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ADD_PRODUCT.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ADD_PRODUCT.setObjectName("ADD_PRODUCT")
        self.prod_id_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.prod_id_LE.setGeometry(QtCore.QRect(280, 110, 341, 31))
        self.prod_id_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.prod_id_LE.setFont(font)
        self.prod_id_LE.setAlignment(QtCore.Qt.AlignCenter)
        self.prod_id_LE.setObjectName("prod_id_LE")
        self.prodname_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.prodname_LE.setGeometry(QtCore.QRect(280, 170, 341, 31))
        self.prodname_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.prodname_LE.setFont(font)
        self.prodname_LE.setAlignment(QtCore.Qt.AlignCenter)
        self.prodname_LE.setObjectName("prodname_LE")
        self.prodqtyLE = QtWidgets.QLineEdit(self.centralwidget)
        self.prodqtyLE.setGeometry(QtCore.QRect(280, 230, 341, 31))
        self.prodqtyLE.setStyleSheet("background-color: rgb(255, 255, 255);")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.prodqtyLE.setFont(font)
        self.prodqtyLE.setAlignment(QtCore.Qt.AlignCenter)
        self.prodqtyLE.setObjectName("prodqtyLE")
        self.Prodprice_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.Prodprice_LE.setGeometry(QtCore.QRect(280, 290, 341, 31))
        self.Prodprice_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Prodprice_LE.setFont(font)
        self.Prodprice_LE.setAlignment(QtCore.Qt.AlignCenter)
        self.Prodprice_LE.setObjectName("Prodprice_LE")
        self.prodtype_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.prodtype_LE.setGeometry(QtCore.QRect(280, 350, 341, 31))
        self.prodtype_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.prodtype_LE.setFont(font)
        self.prodtype_LE.setAlignment(QtCore.Qt.AlignCenter)
        self.prodtype_LE.setObjectName("prodtype_LE")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(390, 410, 121, 28))
        self.submit_button.setStyleSheet("QPushButton{background:LawnGreen;border-style: solid;border-color: black;border-width: 4px;border-radius: 8px}\QPushButton::hover{background:ForestGreen}\QPushButton:pressed{background:GreenYellow}")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.submit_button.clicked.connect(self.update_data)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Update Product"))
        self.Product_Qty.setText(_translate("MainWindow", "Product ID:"))
        self.Product_name.setText(_translate("MainWindow", "Product Name:"))
        self.Product_price.setText(_translate("MainWindow", "Product Quantity:"))
        self.Product_ID.setText(_translate("MainWindow", "Product Price:"))
        self.Product_type.setText(_translate("MainWindow", "Product Type:"))
        self.ADD_PRODUCT.setText(_translate("MainWindow", "UPDATE PRODUCT"))
        self.submit_button.setText(_translate("MainWindow", "SUBMIT"))

class insertWin(QMainWindow):
    def messagebox(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowIcon(QtGui.QIcon('App logo.png'))
        mess.setWindowTitle(title)
        mess.setText(message)
        mess.setStandardButtons(QtWidgets.QMessageBox.Ok|QtWidgets.QMessageBox.Cancel)
        mess.exec_()

        if mess.Ok:
            self.prodtype_LE.clear()
            self.prod_id_LE.clear()
            self.prodname_LE.clear()
            self.Prodprice_LE.clear()
            self.prodqtyLE.clear()
            
    def insert_data(self):
        try:
            ID=self.prod_id_LE.text()
            Name=self.prodname_LE.text()
            qty=self.prodqtyLE.text()
            Price=self.Prodprice_LE.text()
            prod_type=self.prodtype_LE.text()
            params=(ID,Name,qty,Price,prod_type)
            conn = pymysql.connect(host="localhost",port=3306,db="dboragon",user="DBMS",password="12345")
            cursor = conn.cursor()
            cursor.callproc('Insertrow_Sales',params)
            conn.commit()
            conn.close()
        except:
            self.messagebox('Error','Please Enter a value')
        finally:
            self.messagebox('Success','Enter another value')

    def setupUi(self, MainWindow):
        MainWindow.setWindowIcon(QtGui.QIcon('App Logo.png'))
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(653, 455)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(653, 455))
        MainWindow.setMaximumSize(QtCore.QSize(653, 455))
        MainWindow.setSizeIncrement(QtCore.QSize(653, 455))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Background = QtWidgets.QLabel(self.centralwidget)
        self.Background.setGeometry(QtCore.QRect(0, 0, 651, 451))
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.Background.setPixmap(QPixmap('product.png'))
        self.Product_Qty = QtWidgets.QLabel(self.centralwidget)
        self.Product_Qty.setGeometry(QtCore.QRect(40, 90, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Product_Qty.setFont(font)
        self.Product_Qty.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Product_Qty.setObjectName("Product_Qty")
        self.Product_name = QtWidgets.QLabel(self.centralwidget)
        self.Product_name.setGeometry(QtCore.QRect(40, 150, 161, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Product_name.setFont(font)
        self.Product_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Product_name.setObjectName("Product_name")
        self.Product_price = QtWidgets.QLabel(self.centralwidget)
        self.Product_price.setGeometry(QtCore.QRect(40, 210, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Product_price.setFont(font)
        self.Product_price.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Product_price.setObjectName("Product_price")
        self.Product_ID = QtWidgets.QLabel(self.centralwidget)
        self.Product_ID.setGeometry(QtCore.QRect(40, 270, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Product_ID.setFont(font)
        self.Product_ID.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Product_ID.setObjectName("Product_ID")
        self.Product_type = QtWidgets.QLabel(self.centralwidget)
        self.Product_type.setGeometry(QtCore.QRect(40, 330, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Product_type.setFont(font)
        self.Product_type.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Product_type.setObjectName("Product_type")
        self.ADD_PRODUCT = QtWidgets.QLabel(self.centralwidget)
        self.ADD_PRODUCT.setGeometry(QtCore.QRect(220, 20, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ADD_PRODUCT.setFont(font)
        self.ADD_PRODUCT.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ADD_PRODUCT.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ADD_PRODUCT.setObjectName("ADD_PRODUCT")
        self.prod_id_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.prod_id_LE.setGeometry(QtCore.QRect(280, 110, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.prod_id_LE.setFont(font)
        self.prod_id_LE.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.prod_id_LE.setAlignment(QtCore.Qt.AlignCenter)
        self.prod_id_LE.setObjectName("prod_id_LE")
        self.prodname_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.prodname_LE.setGeometry(QtCore.QRect(280, 170, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.prodname_LE.setFont(font)
        self.prodname_LE.setAlignment(QtCore.Qt.AlignCenter)
        self.prodname_LE.setObjectName("prodname_LE")
        self.prodqtyLE = QtWidgets.QLineEdit(self.centralwidget)
        self.prodqtyLE.setGeometry(QtCore.QRect(280, 230, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.prodqtyLE.setFont(font)
        self.prodqtyLE.setAlignment(QtCore.Qt.AlignCenter)
        self.prodqtyLE.setObjectName("prodqtyLE")
        self.Prodprice_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.Prodprice_LE.setGeometry(QtCore.QRect(280, 290, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.Prodprice_LE.setFont(font)
        self.Prodprice_LE.setAlignment(QtCore.Qt.AlignCenter)
        self.Prodprice_LE.setObjectName("Prodprice_LE")
        self.prodtype_LE = QtWidgets.QLineEdit(self.centralwidget)
        self.prodtype_LE.setGeometry(QtCore.QRect(280, 350, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.prodtype_LE.setFont(font)
        self.prodtype_LE.setAlignment(QtCore.Qt.AlignCenter)
        self.prodtype_LE.setObjectName("prodtype_LE")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(390, 410, 121, 28))
        self.submit_button.setStyleSheet("QPushButton{background:LawnGreen;border-style: solid;border-color: black;border-width: 4px;border-radius: 8px}\QPushButton::hover{background:ForestGreen}\QPushButton:pressed{background:GreenYellow}")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.submit_button.clicked.connect(self.insert_data)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ADD Product"))
        self.Product_Qty.setText(_translate("MainWindow", "Product ID:"))
        self.Product_name.setText(_translate("MainWindow", "Product Name:"))
        self.Product_price.setText(_translate("MainWindow", "Product Quantity:"))
        self.Product_ID.setText(_translate("MainWindow", "Product Price:"))
        self.Product_type.setText(_translate("MainWindow", "Product Type:"))
        self.ADD_PRODUCT.setText(_translate("MainWindow", "ADD PRODUCT"))
        self.submit_button.setText(_translate("MainWindow", "SUBMIT"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Mainmenu()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = insertWin()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = update_win()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Transactwin()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
